---
language: node_js
cache:
  directories:
  - "$HOME/.npm"
node_js:
- '10'
install:
- npm ci
- npm install -g codecov
script:
- npm run travis:verify
- codecov
after_success:
- curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
env:
  global:
  - NODE_OPTIONS="--max-old-space-size=4096 --max_old_space_size=4096"
