---
language: node_js
cache:
  directories:
  - "$HOME/.npm"
node_js:
- '10'
install:
- npm ci
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm run travis:verify
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
after_success:
- curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
env:
  global:
  - NODE_OPTIONS="--max-old-space-size=4096 --max_old_space_size=4096"
