# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json

apiVersion: v1
kind: Template
metadata:
  name: sources-ui
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: sources
    spec:
      feoConfigEnabled: true
      bundleSegments:
        - segmentId: sources-settings
          bundleId: settings
          position: 100
          navItems:
            - id: integrations
              title: Integrations
              icon: PlaceholderIcon
              href: /settings/integrations
      envName: ${ENV_NAME}
      title: Sources
      deploymentRepo: https://github.com/RedHatInsights/sources-ui
      API:
        versions:
          - v3.1
      frontend:
        paths:
          - /apps/sources
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: "/apps/sources/fed-mods.json"
        defaultDocumentTitle: "Sources | Settings"
        modules:
          - id: "sources"
            module: "./RootApp"
            routes:
              - pathname: /settings
              - pathname: /settings/integrations

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/sources-ui
